apiVersion: v1
kind: Service
metadata:
  name: numbers-web
spec:
  selector:
      app: lab-numbers-web
      version: v2
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: numbers-api
spec:
  selector:
      app: lab-numbers-api
      version: v1
  type: ClusterIP
  ports:
    - port: 80